[build]
  command = "bash netlify_build.sh"
  publish = "client/build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
  # Opcional: subí el “soft memory limit” si ves OOM (no siempre hace falta)
  # NETLIFY_BUILD_DEBUG = "true"
