[build]
  base    = "client"
  command = "bash netlify_build.sh"
  publish = "build/web"

[build.environment]
  # Opcional: fijar versión si te sirve
  # FLUTTER_VERSION = "3.22.2"

# Opcional: evitar que Netlify auto-detecte frameworks ajenos
[plugins]
  # (vacío)
